/* Auto-generated by split_sources.py — do not edit by hand. */
/* Simulates three on-prem hospital systems on one SQL Server host. */
SET NOCOUNT ON;
GO

IF DB_ID('OHN_EHR') IS NULL CREATE DATABASE OHN_EHR;
GO
USE OHN_EHR;
GO

IF OBJECT_ID('dbo.patient') IS NOT NULL DROP TABLE dbo.patient;
CREATE TABLE dbo.patient (
    [patient_id] VARCHAR(20) NOT NULL,
    [first_name] NVARCHAR(60),
    [last_name] NVARCHAR(60),
    [date_of_birth] VARCHAR(12),
    [gender] VARCHAR(10),
    [health_card_number] VARCHAR(20),
    [postal_code] VARCHAR(12),
    [primary_phone] VARCHAR(24),
    [preferred_language] NVARCHAR(40),
    [deceased_indicator] CHAR(1),
    [last_modified_ts] DATETIME2(3)
);
GO
CREATE INDEX IX_patient_last_modified_ts ON dbo.patient ([last_modified_ts]);
GO

IF OBJECT_ID('dbo.admission') IS NOT NULL DROP TABLE dbo.admission;
CREATE TABLE dbo.admission (
    [admission_id] VARCHAR(20) NOT NULL,
    [encounter_id] VARCHAR(20),
    [patient_id] VARCHAR(20),
    [attending_physician_id] VARCHAR(20),
    [department_id] VARCHAR(30),
    [hospital_id] VARCHAR(10),
    [admission_ts] DATETIME2(3),
    [discharge_ts] DATETIME2(3) NULL,
    [expected_discharge_ts] DATETIME2(3) NULL,
    [admission_type] VARCHAR(10),
    [discharge_disposition_code] VARCHAR(10),
    [primary_diagnosis_code] VARCHAR(20),
    [payer_id] VARCHAR(10),
    [last_modified_ts] DATETIME2(3)
);
GO
CREATE INDEX IX_admission_last_modified_ts ON dbo.admission ([last_modified_ts]);
GO

IF OBJECT_ID('dbo.bed_assignment') IS NOT NULL DROP TABLE dbo.bed_assignment;
CREATE TABLE dbo.bed_assignment (
    [admission_id] VARCHAR(20),
    [encounter_id] VARCHAR(20),
    [bed_id] VARCHAR(30),
    [assignment_start_ts] DATETIME2(3),
    [assignment_end_ts] DATETIME2(3) NULL,
    [assignment_reason] VARCHAR(30)
);
GO

IF OBJECT_ID('dbo.diagnosis') IS NOT NULL DROP TABLE dbo.diagnosis;
CREATE TABLE dbo.diagnosis (
    [encounter_id] VARCHAR(20),
    [patient_id] VARCHAR(20),
    [diagnosis_code] VARCHAR(20),
    [diagnosis_rank] SMALLINT,
    [diagnosis_type] VARCHAR(20),
    [is_primary] BIT,
    [is_present_on_admission] BIT,
    [diagnosis_date] DATE
);
GO

IF OBJECT_ID('dbo.emergency_visit') IS NOT NULL DROP TABLE dbo.emergency_visit;
CREATE TABLE dbo.emergency_visit (
    [ed_visit_id] VARCHAR(20) NOT NULL,
    [encounter_id] VARCHAR(20),
    [patient_id] VARCHAR(20),
    [hospital_id] VARCHAR(10),
    [department_id] VARCHAR(30),
    [arrival_ts] DATETIME2(3),
    [triage_ts] DATETIME2(3) NULL,
    [physician_seen_ts] DATETIME2(3) NULL,
    [admit_decision_ts] DATETIME2(3) NULL,
    [bed_assigned_ts] DATETIME2(3) NULL,
    [departure_ts] DATETIME2(3) NULL,
    [triage_score] VARCHAR(4),
    [arrival_mode] VARCHAR(20),
    [triage_diagnosis_code] VARCHAR(20),
    [left_without_being_seen] BIT,
    [resulted_in_admission] BIT,
    [payer_id] VARCHAR(10),
    [last_modified_ts] DATETIME2(3)
);
GO
CREATE INDEX IX_emergency_visit_last_modified_ts ON dbo.emergency_visit ([last_modified_ts]);
GO

IF DB_ID('OHN_SCHED') IS NULL CREATE DATABASE OHN_SCHED;
GO
USE OHN_SCHED;
GO

IF OBJECT_ID('dbo.patient') IS NOT NULL DROP TABLE dbo.patient;
CREATE TABLE dbo.patient (
    [patient_ref] VARCHAR(20) NOT NULL,
    [given] NVARCHAR(60),
    [surname] NVARCHAR(60),
    [dob] VARCHAR(12),
    [sex] VARCHAR(10),
    [health_card] VARCHAR(20),
    [postal] VARCHAR(12),
    [contact_phone] VARCHAR(24),
    [modified_at] DATETIME2(3)
);
GO
CREATE INDEX IX_patient_modified_at ON dbo.patient ([modified_at]);
GO

IF OBJECT_ID('dbo.appointment') IS NOT NULL DROP TABLE dbo.appointment;
CREATE TABLE dbo.appointment (
    [appointment_id] VARCHAR(20) NOT NULL,
    [patient_ref] VARCHAR(20),
    [doctor_id] VARCHAR(20),
    [department_id] VARCHAR(30),
    [hospital_id] VARCHAR(10),
    [booking_ts] DATETIME2(3),
    [scheduled_ts] DATETIME2(3),
    [scheduled_duration_min] INT,
    [appointment_type] VARCHAR(40),
    [is_first_visit] BIT,
    [is_virtual] BIT,
    [checkin_ts] DATETIME2(3) NULL,
    [seen_ts] DATETIME2(3) NULL,
    [checkout_ts] DATETIME2(3) NULL,
    [cancellation_ts] DATETIME2(3) NULL,
    [cancelled_by] VARCHAR(20),
    [status_code] VARCHAR(30),
    [modified_at] DATETIME2(3)
);
GO
CREATE INDEX IX_appointment_modified_at ON dbo.appointment ([modified_at]);
GO

IF OBJECT_ID('dbo.appointment_status_history') IS NOT NULL DROP TABLE dbo.appointment_status_history;
CREATE TABLE dbo.appointment_status_history (
    [appointment_id] VARCHAR(20),
    [status_code] VARCHAR(30),
    [status_ts] DATETIME2(3)
);
GO

IF DB_ID('OHN_FIN') IS NULL CREATE DATABASE OHN_FIN;
GO
USE OHN_FIN;
GO

IF OBJECT_ID('dbo.patient_account') IS NOT NULL DROP TABLE dbo.patient_account;
CREATE TABLE dbo.patient_account (
    [account_holder_id] VARCHAR(20) NOT NULL,
    [first_nm] NVARCHAR(60),
    [last_nm] NVARCHAR(60),
    [birth_dt] VARCHAR(12),
    [gender_cd] VARCHAR(10),
    [hc_number] VARCHAR(20),
    [zip_postal] VARCHAR(12),
    [phone_number] VARCHAR(24),
    [update_dt] DATETIME2(3)
);
GO
CREATE INDEX IX_patient_account_update_dt ON dbo.patient_account ([update_dt]);
GO

IF OBJECT_ID('dbo.invoice') IS NOT NULL DROP TABLE dbo.invoice;
CREATE TABLE dbo.invoice (
    [invoice_id] VARCHAR(20) NOT NULL,
    [patient_id] VARCHAR(20),
    [encounter_id] VARCHAR(20),
    [hospital_id] VARCHAR(10),
    [payer_id] VARCHAR(10),
    [invoice_date] DATE,
    [service_date] DATE,
    [total_amount] DECIMAL(18,2),
    [update_dt] DATETIME2(3)
);
GO
CREATE INDEX IX_invoice_update_dt ON dbo.invoice ([update_dt]);
GO

IF OBJECT_ID('dbo.invoice_line') IS NOT NULL DROP TABLE dbo.invoice_line;
CREATE TABLE dbo.invoice_line (
    [invoice_id] VARCHAR(20),
    [invoice_line_number] INT,
    [patient_id] VARCHAR(20),
    [department_id] VARCHAR(30),
    [hospital_id] VARCHAR(10),
    [payer_id] VARCHAR(10),
    [encounter_id] VARCHAR(20),
    [service_code] VARCHAR(20),
    [service_category] NVARCHAR(60),
    [quantity] DECIMAL(12,2),
    [charge_amount] DECIMAL(18,2),
    [discount_amount] DECIMAL(18,2),
    [tax_amount] DECIMAL(18,2),
    [net_amount] DECIMAL(18,2),
    [payment_amount] DECIMAL(18,2),
    [outstanding_amount] DECIMAL(18,2)
);
GO
